### ISSUE TITLE
Clicking 'next', 'prev' or 'close' opens a new tab

### ISSUE THREAD

**Issue by fiedl** [lokesh/lightbox2#20]
I'm using lightbox 2.51 with jquery 1.7.2 in a ruby-on-rails app.
Testing in chromium 19.0.1084.46 (0) on archlinux.

When clicking on the 'next', 'prev' or 'close' links, after executing the click event in javascript, a blank tab opens.  The browser, apparently, opens a new tab when clicking on a link without `href="#"` attribute.

Therefore, I was able to fix this, using this script:

``` coffee
# app/assets/fix-lightbox.js.coffee
jQuery ->
  selector = ".lb-next,.lb-prev,.lb-close"
  $( selector ).live( "mouseenter", ->
    $( selector ).attr( "href", "#" ) # otherwise click will open new tab                                                             
  )
```

Has anyone else experienced this issue?
Or maybe I'm doing something wrong?

**Comment by Galacticstarkiller** [comment]
I had this bug recently. I reloaded my browser in incognito mode and the issue went away for the next and previous buttons. The close button continued to open a new tab. I was forced to remove the 'X' close button. Since I've gotten lightbox to work the close button has had the open tab problem. I feel the next and previous button issue could have been a cached version stuck in the browser.
