### ISSUE TITLE
Overlay Image

### ISSUE THREAD

**Issue by afoketunji** [lokesh/lightbox2#364]
Overlay image doesn't have an alt. Hardcoding it into lightbox.js won't really work because all the images will carry the same alt tag. Please help. Thanks.

**Comment by gcundiff** [comment]
I added code to set the alt and title properties of the overlay image and the navigation icons (prev, next, close) for accessibility.  I am using Lightbox v2.8.2.  I use the title of the original image, set that in the addToAlbum function (lines 156-168).  I am also setting the link to the source of the original image instead of the link, but you can ignore that change.  Lines 344-351 set the alt and title of all the navigation images.  Lines 395-399 set the alt and title of the overlay image.
[lightbox.txt](https://github.com/lokesh/lightbox2/files/723966/lightbox.txt)

**Comment by richandhandsomeman** [comment]
I've tried your code, it doesn't work for me. I'm using 2.51, but in my case title attribute of <a> tag provides caption for overlay image. I need 'alt' and 'title' for overlay picture. If you know how to make it work, please let me know!

**Comment by lokesh** [comment]
Support for per-image alt attributes, separate from the title attr incoming in next release:
https://github.com/lokesh/lightbox2/pull/609

I'll close this issue once it is released.

**Comment by lokesh** [comment]
Resolved: https://github.com/lokesh/lightbox2/releases/tag/v2.10.0
