### ISSUE TITLE
v.2.8.0  body

### ISSUE THREAD

**Issue by dmaglio** [lokesh/lightbox2#462]
With last version, won't append div into body, v.2.7.4 works correctly
Xubuntu 15.04
Firefox 38.0

**Comment by lokesh** [comment]
I was unable to recreate this issue in Firefox 38 and 39 on OSX.

Are you seeing this error still? Can you recreate it on the main Lightbox page? http://lokeshdhakar.com/projects/lightbox2/

**Comment by dmaglio** [comment]
demo page work correctly, but the same code in my demo site and 2.8 no, same code and 2.7.4 yes

**Comment by lokesh** [comment]
This looks to be an issue with your demo site setup vs an actual bug. Let's move this isse to Stackoverflow from Github. Can you add a question on http://stackoverflow.com, make sure to add the ```lightbox2``` tag.

Please include the following details in your question:

- What version of Lightbox2 you are using
- Information on which browsers and operating systems you have reproduced the bug on
- Steps to reproduce the bug
- A link to your production site where the bug is visible or all relevant HTML, CSS, and Javascript required to recreate the bug

I'll look into it there and others can also help. Thanks.
