### ISSUE TITLE
Broken Lightbox before <script src="lightbox.js">

### ISSUE THREAD

**Issue by mathishuettl** [lokesh/lightbox2#465]
Anyone knows whats happen there?
![unbenannt](https://cloud.githubusercontent.com/assets/9340538/8594581/55c8a010-2642-11e5-8dbb-569ff4350b3c.PNG)

right before the <script> tag that includes lightbox there is a lightbox ...

**Comment by lokesh** [comment]
@mathishuettl 

Information on how to get help: http://lokeshdhakar.com/projects/lightbox2/#help

If you post your question on Stackoverflow, make sure you provide the following information:

- What version of Lightbox2 you are using
- Information on which browsers and operating systems you have reproduced the bug on
- Steps to reproduce the bug
- A link to your production site where the bug is visible or all relevant HTML, CSS, and Javascript required to recreate the bug
