### ISSUE TITLE
loading last picture instead of first

### ISSUE THREAD

**Issue by hugoesp** [lokesh/lightbox2#469]
Hello,

I think there's a bug when you make an array of pics with. It basically opens the last one.
anyone else had this mistake?

Cheers!

**Comment by lokesh** [comment]
Another user reported this issue. Their fix was related to the placement of the other images vs the link to activate Lightbox. See here:
https://github.com/lokesh/lightbox2/issues/459

If that doesn't fix the issue, please do the following fdetails:

- What version of Lightbox2 you are using
- Information on which browsers and operating systems you have reproduced the bug on
- Steps to reproduce the bug
- A link to your production site where the bug is visible or all relevant HTML, CSS, and Javascript required to recreate the bug

**Comment by hugoesp** [comment]
the issue continues coz I have not target an image but a link so even if I exchange the target it will become the last on the list.

you can review here the bug:
http://ondiversion.net/vialighting/#content

in the code the issue begins in the line 106.

I'm using the latest version.

**Comment by lokesh** [comment]
The following is not valid HTML:

```html
<a href="css/images/project1.jpg" data-lightbox="projects">
	<a href="css/images/project2.jpg" data-lightbox="projects">
		<a href="css/images/project3.jpg" data-lightbox="projects">
			<div class="botonLink">
				<div class="buttonGo">Link					
				</div>
			</div>
</a></a></a>
```

You cannot nest ```<a>``` tags. Here is the error as reported by the W3C Validator:
<img width="879" alt="screen shot 2015-07-21 at 11 40 36 am" src="https://cloud.githubusercontent.com/assets/51469/8805102/687a0816-2f9d-11e5-83d9-b704000b28e2.png">

Change your code to the following:

```html
<a href="css/images/project1.jpg" data-lightbox="projects">
			<div class="botonLink">
				<div class="buttonGo">Link					
				</div>
			</div>
<a/>
<a href="css/images/project2.jpg" data-lightbox="projects"></a>
<a href="css/images/project3.jpg" data-lightbox="projects"></a>

**Comment by hugoesp** [comment]
Sweet!

Thanks for your help!

Have a great day ;)
