### ISSUE TITLE
Plugin is great but incredibly limited

### ISSUE THREAD

**Issue by r3wt** [lokesh/lightbox2#483]
I propose the following change:

add onchange event - useful for people who want to reposition the lightbox and or add additional content inside of the lightbox.

I can make the changes and submit a pr, but i won't waste my time unless its going to be accepted.

**Comment by lokesh** [comment]
@r3wt I'm not adding new features except for some improved mobile interactions to Lightbox2. It is otherwise in maintenance mode.

I am beginning to brainstorm what v3 would look like and providing event callbacks and other hooks for devs is definitely on the list.

https://github.com/lokesh/lightbox2#v30---in-planning-phase
