### ISSUE TITLE
Chrome and Firefox fitImagesInViewport Problems

### ISSUE THREAD

**Issue by eSilverStrike** [lokesh/lightbox2#514]
I have images that are larger width and height wise of the viewports. With MS Edge it works fine but with Chrome and Firefox it does not. The windowWidth and windowHeight calculations are not correct as the height of the image always extends beyond the viewport. The width is fine.

I could not reproduce this error on your demo site.

To fix this I change the following lines starting at 243 in lightbox.js from:

`
windowWidth    = $(window).width();
windowHeight   = $(window).height();
`

to

`
windowWidth    = window.innerWidth;
windowHeight   = window.innerHeight;
`

I am not sure why the original way is not working.

**Comment by lokesh** [comment]
Reviewing old issues.

Since this issue was not reproducible on the [demo site](http://lokeshdhakar.com/projects/lightbox2/) I am going to assume this is not a bug in the script but a conflict with the local set up. Though this could still be a legit bug; I have not heard similar reports.

Closing for now. I can reopen if others reproduce and can isolate the issue.

**Comment by JboyJW** [comment]
I experienced this exact same issue and the solution above fixed it.  My full size images are 800px by 1000px, and the image always showed full size and had to scroll.  Works as expected after altering the js code as above.

**Comment by joshcorne** [comment]
Thanks @eSilverStrike, your alterations solved the issue for me too. 

Running: Firefox 118 on Ubuntu 23.10.

**Comment by charlesdadu** [comment]
It worked for me too, thank you!
