### ISSUE TITLE
Capture ESCAPE keypress

### ISSUE THREAD

**Issue by rkyoku** [lokesh/lightbox2#663]
When pressing the `ESCAPE` key, lightbox closes itself. Nice! :)

However, it does not capture the event, which therefore bubbles up in another plugin I have, and I cannot modify the plugin code.

I will try and modify lightbox code instead, whilst waiting for an input on this one.

EDIT: more info: I am using MaterializeCSS modals. Inside some of them, I have some images that I use lightbox with. When lightbox is open on top of the modal and pressing the ESCAPE key (which closes the modal by default), lightbox should be the first to handle the event, and it should (IMHO) catch it and not let it propagate. That way, the modal does not closes whenever I close lightbox.

Thanks in advance!

Best,

**Comment by lokesh** [comment]
@rkyoku I do understand your usecase, but the solution isn't as simple as stopping propagation of the event. Since they are attached to the document. 

I'm going to investigate an update to help for your scenario. The changes I am planning:
1. Attach the keyboard event handlers to the two root notes of the Lightbox script output: the overlay and the lightbox image container.
2. On opening Lightbox, update the active/focused element from the trigger to the lightbox overlay which has the new handlers.

**Comment by Sahil107-coder** [comment]
sir, 
I am having trouble creating a website with LightBox

**Comment by RodDev** [comment]
I'm having issues with .webp images any help setting this up to work with lightbox, thx.
