### ISSUE TITLE
click on the link and open the attached image

### ISSUE THREAD

**Issue by susl16c** [lokesh/lightbox2#741]
click on the link and open the attached image ?

**Comment by OGFaisalN** [comment]
Yes. Lightbox 2 is used to open the image in a lightbox as an alternative to opening the image in a new tab (by simply visiting the image source URL). Lightbox 2 uses the HTML link tag `<a>` and utilizes it's `href` property, so that when you click on the link it opens the lightbox instead of the link. This is useful for simulating a cursor change on link hover (like `cursor: pointer`), or other CSS you have applied for links.

**Comment by Creekmore108** [comment]
I'm having the same issue in a Laravel11 Livewire3 project. I've included the JS & CSS files as well as trying the CDN approach with the same results. I get the image in a new screen with a black background.
