### ISSUE TITLE
Lightbox loader shows up in bottom center of screen

### ISSUE THREAD

**Issue by clouddueling** [lokesh/lightbox2#97]
When the height of my window is large enough this appears:

![screen shot 2013-09-05 at 3 15 08 pm](https://f.cloud.github.com/assets/1400735/1092306/da770822-1679-11e3-9971-0bd18963f5a0.png)

When I change left to: -10000px then it disappears.  I don't know the codebase well enough to know if it causes other problems but appears to work.
![screen shot 2013-09-05 at 3 24 14 pm](https://f.cloud.github.com/assets/1400735/1092308/ebd3f21a-1679-11e3-8980-6db0d672d4bb.png)

**Comment by phbernard** [comment]
I could observe this issue with LB 2.8.2, by calling `lightbox.init()` twice. First time, everything works as expected. Second time, the loader is shown as described by @clouddueling.

Fixes:

  - Call `lightbox.init()` only once. Definitely the right thing to do, since calling it twice is unnecessary. Maybe a check could be done internally by LB to avoid the mistake (on second call, throw an error or do nothing).
  - @clouddueling's "set left to -10000px" workaround also works, although this is obviously not the preferred solution here.
